### ISSUE TITLE
AdaBelief issues

### ISSUE THREAD

**Issue by cossio** [FluxML/Flux.jl#1962]
As far as I can see, the current implementation of AdaBelief is not doing any bias correction, which is one of the main selling points of ADAM. One can compare this line of ADAM:

https://github.com/FluxML/Flux.jl/blob/25457f52c37d1c78f8bc6c28439f847ffa3b654d/src/optimise/optimisers.jl#L183-L186

where you see the betas are raised to the iteration number for the bias correction. In contrast, in AdaBelief:

https://github.com/FluxML/Flux.jl/blob/25457f52c37d1c78f8bc6c28439f847ffa3b654d/src/optimise/optimisers.jl#L536-L538

I don't see this is done.

Also, the role of epsilon seems inconsistent with the paper. But see also https://github.com/juntang-zhuang/Adabelief-Optimizer/issues/61.

I can do a PR but I would like to make sure I understand the original implementation first. Pinging @willtebbutt

**Comment by willtebbutt** [comment]
I implemented this sufficiently long ago, that I no longer have any idea whether the implementation makes sense. If you believe the implementation isn't correct, I am inclined to believe you.

**Comment by darsnack** [comment]
Yeah I think you're right. The bias correction is missing and there's an epsilon missing. A PR would be appreciated!

**Comment by cossio** [comment]
I just realized in an earlier version of the draft they omitted the bias correction from the presentation, https://arxiv.org/pdf/2010.07468v1.pdf (though it's present in appendix).

The use of epsilon however is still not clear to me, they seem to have moved it around in different versions of the paper

**Comment by cossio** [comment]
@darsnack Do I need some approval to get CI running on https://github.com/FluxML/Flux.jl/pull/1963?
